version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    executor: ruby/default
    steps:
      - checkout
      - run: ls
      - run:
      name: Install dependencies
      command: |
        apk add --no-cache \
          py-pip=9.0.0-r1
        pip install \
          docker-compose==1.12.0 \
          awscli==1.11.76
      # - run: docker build  -f ./Dockerfile  -t birchbox/test:latest  ./
      # - run: docker images


